# 线性代数

In [33]:
import numpy as np

## 矩阵与向量的乘积
### 点积
`dot(a,b,out=None)` 计算两个数组的点积：
 1）如果 `a` 和 `b` 都是一维数组，那么点积即为内积（没有共轭）；

In [34]:
np.dot(3, 4)

12

In [35]:
np.dot(3j, 4j)

(-12+0j)

 2）如果`a` 和 `b` 都是二维数组，那么使用矩阵乘法 `a @ b` ;

In [36]:
a = [[1, 0], [0, 1]]
b = [[4, 1], [2, 2]]
np.dot(a, b)

array([[4, 1],
       [2, 2]])

 3）如果`a` 或 `b` 是标量（维数为`0`），那么其点积等价于乘，可以使用 `numpy.multiply(a,b)`  或 `a*b` ；

In [37]:
a = 4
b = [[4,1],[2,2]]
np.dot(a,b)

array([[16,  4],
       [ 8,  8]])

 4）如果`a` 是一维数组， `b` 是`N`维数组，那么点积是 `a` 与 `b` 的最后一个轴的积的和；

In [38]:
a = [3,4,5]
b = [[1,2,3],[4,5,6],[7,8,9]]
np.dot(a,b)

array([54, 66, 78])

 5）如果`a` 是`N`维数组， `b` 是`M-d`维数组(M≥2)，那么点积为 `a` 的最后一个轴与 `b` 的倒数第二条轴的乘机的和：
 `dot(a,b)[i,j,k,m] = sum(a[i,j,:]*b[k,:,m])`

In [39]:
a = [[1,5,7],[2,4,6],[3,6,9],[4,8,10]]
b = [[1,2,3],[4,5,6],[7,8,9]]
np.dot(a,b)


array([[ 70,  83,  96],
       [ 60,  72,  84],
       [ 90, 108, 126],
       [106, 128, 150]])

`linalg.multi_dot(arrays, *, out=None)`函数，在单个函数调用中计算两个或多个数组的点积，同时自动选择最快的求值顺序。
使用该函数时需要注意的是，如果第一个参数是一维数组，它被视为行向量。如果最后一个参数是一维数组，则将其视为列向量。
其他参数必须是二维的。

下面我们通过一个例子学习使用 `linalg.multi_dot(arrays, *, out=None)` 函数：

In [40]:
from numpy.linalg import multi_dot

In [41]:
A = np.random.random((10000, 100))
B = np.random.random((100, 1000))
C = np.random.random((1000, 5))
D = np.random.random((5, 333))

In [42]:
_ = multi_dot([A, B, C, D])
_

array([[29258.56199495, 39185.76250743, 24831.33335922, ...,
        32218.47313706, 49684.46713456, 22935.23821755],
       [27709.83193917, 37113.69763102, 23518.20177806, ...,
        30512.01252248, 47060.32181675, 21714.06820096],
       [30923.66123875, 41400.43468792, 26235.57546294, ...,
        34030.73408076, 52492.73599524, 24230.36608396],
       ...,
       [30037.91721463, 40225.74401239, 25493.36791348, ...,
        33065.16482832, 51002.93827961, 23539.62618817],
       [32787.66087443, 43892.23116514, 27817.26221112, ...,
        36072.93205314, 55650.19508135, 25687.60971541],
       [32347.16027985, 43328.5110721 , 27457.63882012, ...,
        35623.51338682, 54936.40902548, 25354.31087954]])

我们也可以使用 `vdot(a,b,/)` 函数，返回两个向量的点积。
需要注意的是，`vdot` 处理多维数组的方式与 `dot` 不同：`vdot`不执行矩阵乘积，而是首先将输入参数扁平化为一维向量。
因此，`vdot`只能用于向量。

In [43]:
a = np.array([1+2j,3+4j])
b = np.array([5+6j,7+8j])
np.vdot(a, b)

(70-8j)

In [44]:
np.vdot(b, a)

(70+8j)

当 `a` 和 `b` 是更高维度的数组时，输出结果依旧是扁平化的一维向量：

In [45]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
np.vdot(a, b)

70

In [46]:
np.vdot(b, a)

70

In [47]:
1*5 + 2*6 + 3*7 + 4*8

70